version: '3'
services:

    mongo:
        image: mongo
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
    go:
        restart: always
        ports:
            - "8081:8080"
        links:
            - mongo
        build:
            dockerfile: Dockerfile
            context: .